name: Workflow
on:
  push:
    branches:
      - feat-sast

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: build
      run: |
        chmod 777 gradlew
        ./gradlew build

    - name: Validando existencia del proyecto en sonar
      run: |
        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'    
        if [ $? -ne 0 ]; then
          echo "El proyecto ya existe en SonarCloud"
        else
          echo "Proyecto creado exitosamente en SonarCloud"
          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
        fi
      
