name: Workflow
on:
  push:
    branches:
      - feat-sast

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: build
      run: |
        chmod 777 gradlew
        #./gradlew build

    - name: Validando existencia de proyecto en SonarCloud
      id: validateProjectOnSonar
      run: |
        #pwd
        #ls -R
        set +e
        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
        if [ $? -ne 0 ]; then
          echo "Proyecto ya existe en Sonarcloud"
          echo "::set-output name=proyectoExiste::1"
        else
          echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
          
          echo "Se establece rama main como rama por defecto"
          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
        fi
        set -e
    
    - name: Validando tipo de proyecto
      run: | 
        if [ -f "build.gradle" ]
        then
          if grep -q 'id "org.sonarqube" version "3.3"' build.gradle
          then
            echo "El plugin de SonarCloud ya está presente en build.gradle"
          else
            sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
            echo "Plugin de SonarCloud agregado a build.gradle"
            cat build.gradle
          fi
        else
          echo "build.gradle no encontrado. Asegúrate de que el proyecto sea un proyecto Java con Gradle."
          exit 1
        fi
    
    - name: Ejecutando SonarCloud
      run: |
        ./gradlew sonarqube \
          -Dsonar.projectKey=${{ github.event.repository.name }} \
          -Dsonar.organization=devsecopsusach \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.branch.name=main

    - name: Validando resultado de SonarCloud
      run: |
        idanalisis=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
        idanalisisParse=$(echo "$idanalisis" | jq .current.analysisId | sed -e 's/^"//' -e 's/"$//')
        echo "ID del análisis: $idanalisisParse"
        qualitygate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/qualitygates/project_status?analysisId=$idanalisisParse')
        qualitygateStatus=$(echo "$qualitygate" | jq .projectStatus.status | sed -e 's/^"//' -e 's/"$//')
        case $qualitygateStatus in
          *"OK"*)
            echo "Calidad del código: OK"
            ;;
          *"ERROR"*)
            echo "Calidad del código: ERROR"
            exit 1
            ;;
          *"WARN"*)
            echo "Calidad del código: WARN"
            exit 1
            ;;
          *"NONE"*)
            echo "Estado NONE: $qualitygateStatus"
            exit 1
            ;;
        esac


  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      with:  
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@master
      with:
        name: dependency-check-report
        path: ${{github.workspace}}/reports